// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// detR
Rcpp::NumericVector detR(Rcpp::NumericVector r, int param, const arma::mat& R, arma::mat R_);
RcppExport SEXP _Rmodule_detR(SEXP rSEXP, SEXP paramSEXP, SEXP RSEXP, SEXP R_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type param(paramSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R_(R_SEXP);
    rcpp_result_gen = Rcpp::wrap(detR(r, param, R, R_));
    return rcpp_result_gen;
END_RCPP
}
// apesOfWrath
double apesOfWrath(double rho, const arma::mat& intervals, double sigma);
RcppExport SEXP _Rmodule_apesOfWrath(SEXP rhoSEXP, SEXP intervalsSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type intervals(intervalsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(apesOfWrath(rho, intervals, sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rmodule_detR", (DL_FUNC) &_Rmodule_detR, 4},
    {"_Rmodule_apesOfWrath", (DL_FUNC) &_Rmodule_apesOfWrath, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rmodule(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
