# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detR <- function(r, param, R, R_) {
    .Call('_Rmodule_detR', PACKAGE = 'Rmodule', r, param, R, R_)
}

apesOfWrath <- function(rho, intervals, sigma) {
    .Call('_Rmodule_apesOfWrath', PACKAGE = 'Rmodule', rho, intervals, sigma)
}

